require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.statusbar")
require("plugins.auto-pairs")
require("plugins.vscode")
require("plugins.myPlugs")
require("plugins.fzf-lua")
require("plugins.harpoon")
