require("plugins.gitsigns")
require("plugins.lsp")
require("plugins.statusbar")
require("plugins.auto-pairs")
require("plugins.markdown")
require("plugins.telescope")
require("plugins.neogit")
require("plugins.dashboard")
-- require("plugins.alpha")
